.PATH:	${.CURDIR}/NSURL \

SRCS+=	NSCachedURLResponse.m \
		NSHTTPURLResponse.m \
		NSMutableURLRequest.m \
		NSURLAuthenticationChallenge.m \
		NSURLCache.m \
		NSURLConnection.m \
		NSURLConnectionState.m \
		NSURLCredential.m \
		NSURLCredentialStorage.m \
		NSURLDownload.m \
		NSURLError.m \
		NSURLProtectionSpace.m \
		NSURLProtocol.m \
		NSURLRequest.m \
		NSURLResponse.m \
		#NSURLProtocol_http.m \
