.PATH:	${.CURDIR}/URI \

SRCS+=	NSCachedURIResponse.m \
		NSHTTPURIResponse.m \
		NSMutableURIRequest.m \
		NSURIAuthenticationChallenge.m \
		NSURICache.m \
		NSURIConnection.m \
		NSURIConnectionState.m \
		NSURICredential.m \
		NSURICredentialStorage.m \
		NSURIDownload.m \
		NSURIError.m \
		NSURIProtectionSpace.m \
		NSURIProtocol.m \
		NSURIRequest.m \
		NSURIResponse.m \
		#NSURIProtocol_http.m \
