.PATH: ${.CURDIR}/Collections

SRCS+= NSArray.mm \
	   NSArray+functional.m \
	   NSArray+KVC.m \
	   NSCoreArray.mm \
	   NSPointerArray.mm \
	   NSCharacterSet.m \
	   NSConcreteCharacterSet.m \
	   NSData.m \
	   NSCoreData.mm \
	   NSDictionary.mm \
	   NSCoreDictionary.mm \
	   NSSet.mm \
	   NSCoreSet.mm \
	   NSHashTable.mm \
	   NSMapTable.mm \
	   NSIndexSet.mm \
	   NSCountedSet.mm \
